stages:
  - test
  - build

test:
  stage: test
  image: golang:1.10-alpine3.7
  script:
    - go get -v ./...
    - go run server.go
    - go test ./...

build:
  stage: build
  image: docker:17
  services:
    - docker:dind
  script:
    - docker build -t app .
